package com.learnandroid.liuyong.phrasedictionary.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.learnandroid.liuyong.phrasedictionary.db.bean.CustomPhrase;
import com.learnandroid.liuyong.phrasedictionary.db.bean.Phrase;

import com.learnandroid.liuyong.phrasedictionary.db.dao.CustomPhraseDao;
import com.learnandroid.liuyong.phrasedictionary.db.dao.PhraseDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig customPhraseDaoConfig;
    private final DaoConfig phraseDaoConfig;

    private final CustomPhraseDao customPhraseDao;
    private final PhraseDao phraseDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        customPhraseDaoConfig = daoConfigMap.get(CustomPhraseDao.class).clone();
        customPhraseDaoConfig.initIdentityScope(type);

        phraseDaoConfig = daoConfigMap.get(PhraseDao.class).clone();
        phraseDaoConfig.initIdentityScope(type);

        customPhraseDao = new CustomPhraseDao(customPhraseDaoConfig, this);
        phraseDao = new PhraseDao(phraseDaoConfig, this);

        registerDao(CustomPhrase.class, customPhraseDao);
        registerDao(Phrase.class, phraseDao);
    }
    
    public void clear() {
        customPhraseDaoConfig.clearIdentityScope();
        phraseDaoConfig.clearIdentityScope();
    }

    public CustomPhraseDao getCustomPhraseDao() {
        return customPhraseDao;
    }

    public PhraseDao getPhraseDao() {
        return phraseDao;
    }

}
